### ISSUE TITLE
bug with instalation

### ISSUE THREAD

**Issue by pinochico** [Zasilkovna/virtuemart3#2]
Hi,
After instalation I see error:
Warning: copy(/data/www/new11.zelenazeme.cz/public_html/administrator/language/sk-SK/sk-SK.plg_vmshipment_zasilkovna.ini): failed to open stream: No such file or directory in /data/www/new11.zelenazeme.cz/public_html/tmp/install_562f94a977ec0/virtuemart3-master/install.zasilkovna.php on line 25

Rudolf

**Comment by rivfaader** [comment]
Hi Rudolf,

thanks for the report, the warnings should be fixed now.
