### ISSUE TITLE
Chybí možnost zadat rozpětí hmotnosti

### ISSUE THREAD

**Issue by stawebnice** [Zasilkovna/virtuemart3#33]
Zdravím,

aktuálně jde zadat jen jedna hmotnost, ale když potřebuju zadat dvě různé ceny dopravy - např. do 5 kg a od 5 do 10 kg, tak mi to pak na košíku vyhazuje obě možnosti.

Můžete to, prosím, přidat, aby to šlo zadávat?

U doprav ve VM je standardem i možnost rozpětí hodnoty objednávky (min a max), aby to šlo škálovat.

**Comment by packeta** [comment]
Dobrý den,

můžete mi prosím poslat screen vašeho nastavení přepravní metody a screen jak se vám to projeví v košíku, abych si to mohl otestovat ? 

Co se týče minimální a maximální částky - to lze nastavit přímo v detailu přepravní metody (jak píšete je to běžným VM standartem) - viz. screen https://www.evernote.com/l/AKoxb4rP_zpAh54DafpSBq8sJ0Bl12tU2aA - toto vám nefunguje ?

**Comment by stawebnice** [comment]
jasně - u toho druhého mi to na košíku už ani nenabízí to rozkliknutí na popup s výběrem:

![kosik](https://user-images.githubusercontent.com/33102153/130231179-a90d49e9-70cb-4c30-a51c-ef3f88ddd51a.jpg)
![do5](https://user-images.githubusercontent.com/33102153/130231180-dbf4652f-1dfe-4553-bf09-0fa93a2ecfea.jpg)
![do10](https://user-images.githubusercontent.com/33102153/130231183-b2209565-cdd3-4fb2-936d-1b59117bc016.jpg)

**Comment by stawebnice** [comment]
to cenové rozpětí jsem na první záložce našla

**Comment by packeta** [comment]
pošlete mi prosím sem (nebo na email technicka.podpor@zasilkovna.cz) url vašeho eshopu a také screeny s kompletním nastavením přepravní metody (obě záložky).

Pokud chcete mít různé ceny podle hmotnost objednávky (např. do 5kg , 10kg) stačí vám k tomu jedna přepravní metoda Zásilkovny a jednotlivé ceny definovat v části "Pravidla cen".
