### ISSUE TITLE
Plugin is not compatible with any other plugin !

### ISSUE THREAD

**Issue by stAn47** [Zasilkovna/virtuemart3#4]
Plugin is not compatible with any other plugin !
since the function 

plgVmOnSelectCheckShipment

is executed per all enabled Joomla plugins even when they are not configured in Virtuemart, zasilkovna plugin rewrites the virtumeart_payment_id even when it is not used at all, (not configured in Virtuemart but still enabled in Joomla)

suggested update: 
```

public function plgVmOnSelectCheckShipment(VirtueMartCart &$cart)
	{
		// these 2 functions will make sure that this plugin won't interfere with the 3rd party shipment methods
		if (!$this->selectedThisByMethodId ($cart->virtuemart_shipmentmethod_id)) {
			return NULL; // Another method was selected, do nothing
		}
		if (!($method = $this->getVmPluginMethod ($cart->virtuemart_shipmentmethod_id))) {
			return NULL; // Another method was selected, do nothing
		}
		if ($this->OnSelectCheck($cart)) {
		// init the session if not yet initialized: 
		   $session = JFactory::getSession(); 
		
		if ($this->OnSelectCheck($cart)) {
			$session->set('branch_id', JRequest::getInt('branch_id', 0));
			$session->set('branch_currency', JRequest::getVar('branch_currency', ''));
			$session->set('branch_name_street', JRequest::getVar('branch_name_street', ''));
			
		} 
		
		// this will break any 3rd party plugins: 
		//$cart->virtuemart_paymentmethod_id = 0;//reset selected payment. Payment options are shown depending on selected shipment
		    return true; 
		}
		
		return false; 
		
		
	}

```

**Comment by stAn47** [comment]
file includes changes in zasilkovna.php 
- to display the selected branch at the order print view and the order frontend view
- fixed session handling
- fixed interference with 3rd parties

[zasilkovna.zip](https://github.com/Zasilkovna/virtuemart3/files/503133/zasilkovna.zip)

**Comment by matyx** [comment]
Thanks for contributing, we will take a look on it next week

**Comment by rivfaader** [comment]
Proposed solution also addresses #3

**Comment by rivfaader** [comment]
Hey good job @stAn47, thanks for the solution, if you wish to get authored on the commit please submit a pull request. If not, just let us know and we'll implement your changes ourselves.
